config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :loans, only: [:new, :create, :index, :destroy, :update] do

    member do
      patch :keep_to_true
    end
    resources :schedules, only: [:new, :create, :destroy, :update]
  end

    resources :charts, only: [] do
      collection do
        get 'loans_by_borrower'
        get 'initial_capital_by_borrower'
        get 'due_per_period'
      end
    end


namespace :api do
    resources :loans, only: [:create, :index] do
      collection do
        get 'by_day'
      end
    end
end










end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_one :loan

  def self.get_schedule(loan_id)
    Schedule.where(loan_id: loan_id).order(:no)
  end



end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def new
    @loan = Loan.find(params[:loan_id])
    @schedule = Schedule.get_schedule(params[:loan_id])
    if @schedule.first.nil?
      create_schedule(@loan)
      @schedule = Schedule.get_schedule(params[:loan_id])
    end
  end

  private

  def create_schedule(loan) #tout est calculé en cents
    periode = get_periode(loan.frequency_payment)
    capital = loan[:principal]  # en cents
    tx_periode = get_rate(loan[:annual_rate]) / periode
    nb_echeance = loan[:term_length] / 12 * periode
    mensualite = (capital * tx_periode / (1-(1 + tx_periode)**(-nb_echeance))).round # en cents
    dueDate = loan[:first_payment_date]

    principalBalance = capital
    #Case of some month delayed
    i = 1
      if !loan.starting_month_delayed.nil?
        loan.starting_month_delayed.times do
        interestDue = (principalBalance * tx_periode).round
        principalDue = 0
        principalBalance = principalBalance
        dueDate = dueDate + 1.months
        newsch = Schedule.create(loan_id: loan.id, no: i, due_date: dueDate, interest_due: interestDue,
          principal_due: principalDue, payment_due: mensualite, principal_balance: principalBalance)
        i += 1
      end
    end

     # echence à npartir du remboursmenet du capital
    (nb_echeance - 1).times do
      interestDue = (principalBalance * tx_periode).round
      principalDue = (mensualite - interestDue).round
      principalBalance = principalBalance - principalDue
      dueDate = dueDate + (12 / periode).months
      newsch = Schedule.create(loan_id: loan.id, no: i, due_date: dueDate, interest_due: interestDue,
        principal_due: principalDue, payment_due: mensualite, principal_balance: principalBalance)
      i += 1
      end
    # last echeance to get exact capital to reimburse
      interestDue = (principalBalance * tx_periode).round
      principalDue = principalBalance
      mensualite = principalDue + interestDue
      principalBalance = 0
      dueDate = dueDate + (12 / periode).months
      newsch = Schedule.create(loan_id: loan.id, no: i, due_date: dueDate, interest_due: interestDue,
        principal_due: principalDue, payment_due: mensualite, principal_balance: principalBalance)
  end

  def get_periode(frequency)
    case frequency
    when "mensuelles"
      return 12
    when "trimestrielles"
      return 4
    when "semestrielles"
      return 2
    when "annuelles"
      return 1
    end
  end

end

app/views/schedules/new.html.erb
<div class="container amort">
  <div class="row amort_info">
    <div class="col-sm-11">
      <h3>Données et tableau d'amortissement </h3>
    </div>
    <div class="col-sm-1">
      <%= link_to loan_path(@loan), method: :delete do %>
        <i class="fa fa-trash" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="click to delete"></i>
      <% end %>
    </div>
    <div class="col-sm-6">
        <table class="amort_info1" >
          <tr>
            <td>Emprunteur</td>
            <td><%= @loan.lender %></td>
          </tr>
          <tr>
            <td>Prêteur</td>
            <td><%= @loan.borrower %></td>
          </tr>
          <tr>
            <td>Montant d'emprunt </td>
            <td><%= display_amount(@loan.principal)  %></td>

          </tr>
          <tr>
            <td>taux annuel </td>
            <td><%= display_rate(@loan.annual_rate) %></td>
          </tr>
      </table>
    </div>
    <div class="col-sm-6">
        <table class="amort_info2" >
            <tr>
              <td>Last Due Date</td>
              <td><%= display_date(@schedule.last.due_date) %></td>
            </tr>
            <tr>
              <td>Total interest</td>
              <td><%= display_amount(@schedule.inject(0){|sum,line| sum + line.interest_due }) %></td>
            </tr>
            <tr>
              <td>Total Principal</td>
              <td><%= display_amount(@schedule.inject(0){|sum,line| sum + line.principal_due } ) %></td>
            </tr>
        </table>
    </div>
  </div>

  <div class="row amort_row">
    <div class="col-sm-12 text-align ">

      <% if @loan.tokeep == false %>
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <h3>Vérifier le tableau d'amortissement de votre prêt puis : </h3>
            </div>
            <div class="col-sm-6">
                <%= form_tag keep_to_true_loan_path(@loan.id), method: :patch do  %>
                  <%= submit_tag 'Sauvegarder',  class: "btn btntokeep"%>
                 <% end  %>
            </div>
          </div>
        </div>
      <% end %>

      <table class="amort_table" >
        <thead>
          <tr class="title_table">
            <th width="10%">No</th>
            <th>Due Date</th>
            <th>Interest Due</th>
            <th>Principal Due</th>
            <th>Payment Due</th>
            <th>Principal Balance</th>
          </tr>
        </thead>
        <tbody>
          <% @schedule.each do |line| %>
            <tr class="line_table">
              <td><%= line.no %></td>
              <td><%= display_date(line.due_date)%></td>
              <td><%= display_amount(line.interest_due) %></td>
              <td><%= display_amount(line.principal_due)%></td>
              <td><%= display_amount(line.payment_due) %></td>
              <td><%= display_amount(line.principal_balance) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>