config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :loans, only: [:new, :create, :index, :destroy, :update] do

    member do
      patch :keep_to_true
    end
    resources :schedules, only: [:new, :create, :destroy, :update]
  end

    resources :charts, only: [] do
      collection do
        get 'loans_by_borrower'
        get 'initial_capital_by_borrower'
        get 'due_per_period'
      end
    end


namespace :api do
    resources :loans, only: [:create, :index] do
      collection do
        get 'by_day'
      end
    end
end










end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.5) 50%, rgba(0,36,61,0.5) 90%), url(<%= image_path 'sky.png' %>);">
  <div class="banner-content">
    <h1>Welcome to Easy Tool</h1>
    <p>Le bon outil pour vous simplifier la vie</p>
    <a href="#allservices" class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>

<div class="container" id="allservices">
  <div class="row">
     <div class="col-xs-12 col-sm-4">

<!-- ajouter les services  ici -->
      <%= link_to loans_path do %>
        <div class="servicecard" >
          <div class="card-logo">
            <i class="fa fa-database" aria-hidden="true"></i>
          </div>
          <div class="card-description">
            <h2>Dette</h2>
            <p>Vision claire et synthétique</p>
            <p>Ajouter une dette</p>
          </div>
        </div>
      <% end %>
  </div>
</div>