config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :loans, only: [:new, :create, :index, :destroy, :update] do

    member do
      patch :keep_to_true
    end
    resources :schedules, only: [:new, :create, :destroy, :update]
  end

    resources :charts, only: [] do
      collection do
        get 'loans_by_borrower'
        get 'initial_capital_by_borrower'
        get 'due_per_period'
      end
    end


namespace :api do
    resources :loans, only: [:create, :index] do
      collection do
        get 'by_day'
      end
    end
end










end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  has_many :schedules, dependent: :destroy

  validates :lender, presence: true
  validates :borrower, presence: true
  validates :principal, presence: true
  validates :term_length, presence: true
  validates :annual_rate, presence: true
  validates :type_loan, presence: true
  validates :frequency_payment, presence: true # monthly, trimestrial, semestrial, annualy
  validates :first_payment_date, presence: true


  def get_lastDueDate(loan_id)
    sched = Schedule.where(loan_id: loan_id).order(:no)
    return sched.last[:due_date]
  end


end

app/controllers/api/loans_controller.rb
class Api::LoansController < Api::BaseController

# fonction appelé quand on subit le form
def create
  respond_to do |format|
    format.js
  end
end


def by_day
  opts = ['due_date', {range: @start_date..@end_date, format: '%d %b'}]
  method_name = :group_by_day
  if by_year?
    opts[1].merge!({format: '%Y'})
    method_name = :group_by_year
  elsif by_month?
    opts[1].merge!({format: '%b %Y'})
    method_name = :group_by_month
  end
  datas = @data_loans.send(method_name, *opts).count
  render json: [{name: 'count capital', data: datas}].chart_json
end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_user

  def index
    if params["sdate"] != nil
      @sdate = params["sdate"]
    else
      @sdate = Time.now
    end
    @loans = Loan.where(user_id: current_user.id)
    ids = @loans.map { |ll| ll.id }
    @schedules = Schedule.where(loan_id: ids)
  end

  def new
    @loan = Loan.new
    lenders_borrowers
  end

  def create
    lp = loan_params
    lp[:principal] = (lp[:principal].to_f * 100).round
    lp[:annual_rate] = (lp[:annual_rate].to_f * 1000).round
    @loan = Loan.new(lp)
    @loan.user = @user
    if @loan.save
      redirect_to new_loan_schedule_path(@loan.id)
    else
        # @loan.update(lender: "")
        # @loan.update(borrower: "")
      lenders_borrowers
      render :new
    end
  end

  def keep_to_true
    Loan.find(params[:id]).update(tokeep: true)
    Schedule.get_schedule(params[:id]).map { |item| item.update(tokeep: true) }
    destroy_others
  end

  def destroy
    Loan.find(params[:id]).destroy
    redirect_to loans_path
  end

  private

  def set_user
    @user = current_user
  end
  def loan_params
    params.require(:loan).permit(:lender, :borrower, :principal , :term_length, :annual_rate, :type_loan, :frequency_payment, :first_payment_date, :starting_month_delayed)
  end

  def destroy_others
    Loan.where(tokeep: false).each {|loan| loan.destroy }
    redirect_to loans_path
  end

  def lenders_borrowers
    @lenders = Loan.where(user_id: current_user.id).where(tokeep: true).map {|l| l.lender}.uniq
    @lenders << "Autre"
    @borrowers = Loan.where(user_id: current_user.id).where(tokeep: true).map {|l| l.borrower}.uniq
    @borrowers << "Autre"
  end

end

app/helpers/loans_helper.rb
module LoansHelper
  def stat_by(start_date, end_date)
    start_date ||= 10.year.ago
    end_date ||= Time.current

    line_chart by_day_api_loans_path(start_date: start_date, end_date: end_date),
      basic_opts('Capital Due total', start_date, end_date)
  end

  private

  def basic_opts(title, start_date, end_date)
    {
      discrete: true,
      library: {
        title: {text: title, x: -20},
        subtitle: {text: "from #{l(start_date, format: :medium)} to #{l(end_date, format: :medium)}", x: -20},
        yAxis: {
          title: {
            text: 'Count'
          }
        },
        tooltip: {
          valueSuffix: 'capital due'
        },
        credits: {
          enabled: false
        }
      }
    }
  end
end

app/views/loans/_form_new_loan.html.erb
<h1>Saisissez les informations suivantes : </h1>
<%= simple_form_for @loan, wrapper: :horizontal_form, html: { class: 'form-horizontal form-new-loan'} do |f| %>
  <!-- lender -->
  <%= f.input :lender,  input_html: { id: 'lender1'}, collection: @lenders , label: 'Prêteur',  error: 'Lender is mandatory, please specify one'%>
  <div id ="divlender2" class = "hidden">
    <%= f.input :lender,  input_html: { id: 'lender2'}, label: 'Autre prêteur', error: 'Lender is mandatory, please specify one'%>
  </div>
  <!-- borrower  -->
  <%= f.input :borrower, input_html: { id: 'borrower1'},collection: @borrowers ,label: 'Emprunteur', error: 'Borrower is mandatory, please specify one'%>
  <div id ="divborrower2" class = "hidden">
    <%= f.input :borrower,  input_html: { id: 'borrower2'}, label: 'Autre emprunteur', error: 'Borrower is mandatory, please specify one'%>
  </div>
  <%= f.input :principal, label: 'Montant (€)', placeholder: '100 000.50' ,error: 'principal is mandatory, please specify one'%>
  <%= f.input :term_length , label: 'Durée (mois)', placeholder: '120' %>
  <%= f.input :annual_rate, label: 'Taux annuel (%)', placeholder: '1.254'%>
  <%= f.input :type_loan, label: 'Type d emprunt', collection: ["K+I constant"], include_blank: false%>
  <%= f.input :frequency_payment, label: 'Echéances', collection: ["mensuelles", "trimestrielles", "semestrielles", "annuelles"], include_blank: false %>
  <%= f.input :starting_month_delayed, label: 'Différé de remboursement du capital (mois)' %>
  <%= f.input :comment, label: 'Commentaires' %>
  <%= f.input :first_payment_date , as: :string, label: 'Date 1ère échéance', input_html: {class: "datepicker"}  %>
  <%= f.submit value: "Voir le tableau d'amortissement ", class:"btn btn-primary " %>
<% end %>

app/views/loans/_graph.html.erb
<div id="graph">
  <%= stat_by(@start_date, @end_date) %>
</div>

app/views/loans/_recap_tab.html.erb
<h1>Liste de l'ensemble des dettes en date du <%= display_date(Time.now) %></h1>
<div>
  <table class="all_l_table" >
    <thead>
      <tr>
        <th>Emprunteur</th>
        <th>Prêteur</th>
        <th>Capital initial</th>
        <th>Taux annuel</th>
        <th>Capital restant du à ce jour </th>
        <th>Dernière échéance </th>
        <th>Détails</i></th>
      </tr>
    </thead>
    <tbody>
      <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.borrower%></td>
        <td><%= loan.lender%></td>
        <td class="right"><%= display_amount(loan.principal)%></td>
        <td class="right"><%= display_rate(loan.annual_rate)%></td>
        <td class="right"><%= capital_restant_du(loan, Time.now) %></td>
        <td class="right"><%= last_due_date(loan, Time.now) %> </td>
        <td><%= link_to new_loan_schedule_path(loan.id) do %>
          <i class="fa fa-search" aria-hidden="true"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th></th>
        <th></th>
        <th class="right"><%= display_amount(@loans.inject(0){|sum,loan| sum + loan.principal }) %></th>
        <th></th>
        <th class="right"><%= capital_restant_du_total(Time.now) %> </th>
        <th></th>
        <th></th>
      </tr>
    </tfoot>
  </table>
</div>

app/views/loans/index.html.erb
<div class="container indexcontainer">
  <div class="row">
    <div class="col-xs-12">
      <!-- button to add a loan  -->
      <%= link_to new_loan_path do %>
      <i class="fa fa-plus-circle" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Ajouter une dette"></i>
      <% end %>
      <!-- index all loans  -->
      <%= render 'recap_tab' %>


<h1>NEw test highcharts </h1>

<h1>Click tracking</h1>

<div id="event_period" class="row">
  <%= form_tag api_loans_path, remote: true do %>
    <div class="col-sm-1">
      <label for="start_date">Start date</label>
    </div>

    <div class="col-sm-3">
      <div class="input-group">
        <input type="text" class="actual_range form-control datepicker" id="start_date" name="start_date">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
      </div>
    </div>

    <div class="col-sm-1 col-sm-offset-1">
      <label for="end_date">End date</label>
    </div>

    <div class="col-sm-3">
      <div class="input-group">
        <input type="text" class="actual_range form-control datepicker" id="end_date" name="end_date">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
      </div>
    </div>

    <div class="col-sm-2">
      <%= submit_tag 'Show!', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<%= render 'graph' %>


















      <!-- get start date  -->
      <form action="" method="get">
        <!-- <div class="col-sm-3"> -->
          <h1><%= @sdate %></h1>
          <label for="sdate">Choisir la date de référence : </label>
        </div>
        <div class="col-sm-3">
          <div class="input-group">
            <input type="text" class="form-control datepicker" id="sdate" name="sdate" placeholder= <%= @sdate %>>
            <div class="input-group-addon">
              <span class="glyphicon glyphicon-th"></span>
            </div>
          </div>
        </div>
<!--         <input type="submit">
      </form>
      Drop down list to know if it is K / I / K+I
      <form action="" method="get"> -->
        <!-- <div class="col-sm-3"> -->
          <label for="ki">Afficher les graphiques pour K, I, ou K+I </label>
        </div>
        <div class="col-sm-3">
          <select id="ki-choice">
            <option value="cap">capital</option>
            <option value="int">interêt</option>
            <option value="capint">capital + interêt</option>
          </select>
        </div>
        <input type="submit">
      </form>





    </div>
  </div>
</div>





<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <p> </p>
      <p> </p>
      <p> </p>
      <p> </p>
      <%= due_per_period %>
      <p> </p>
      <%= bar_chart @loans.group(:lender).count, height: '500px'%>
      <p> </p>
      <p> </p>
      <%= loans_by_borrower %>
      <p> </p>
      <%= initial_capital_by_borrower %>
    </div>
  </div>
</div>

app/views/loans/new.html.erb
<div class="container container-new-loan">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= render 'form_new_loan' %>
    </div>
</div>
</div>